In [1]:
import pandas as pd
import numpy as np

In [2]:
movies= pd.read_csv(r"C:\Users\abc\Desktop\Bootcamp practice\imdb-top-1000.csv")

In [3]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [4]:
movies.shape

(1000, 10)

In [5]:
movies['Genre'].value_counts()

Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: Genre, dtype: int64

In [6]:
movies[movies.Genre=="Action"]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
979,Lethal Weapon,1987,109,Action,7.6,Richard Donner,Mel Gibson,236894,65207127.0,68.0
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
983,The Warriors,1979,92,Action,7.6,Walter Hill,Michael Beck,93878,22490039.0,65.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0

In [12]:
# movies.groupby('Genre').groups.get_group('Animation')
movies.groupby('Genre').get_group('Animation')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
46,Hotaru no haka,1988,89,Animation,8.5,Isao Takahata,Tsutomu Tatsumi,235231,150734678.0,94.0
56,Kimi no na wa.,2016,106,Animation,8.4,Makoto Shinkai,Ryûnosuke Kamiki,194838,5017246.0,79.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
...,...,...,...,...,...,...,...,...,...,...
956,Mulan,1998,88,Animation,7.6,Tony Bancroft,Barry Cook,256906,120620254.0,71.0
971,Omohide poro poro,1991,118,Animation,7.6,Isao Takahata,Miki Imai,27071,453243.0,90.0
976,The Little Mermaid,1989,83,Animation,7.6,Ron Clements,John Musker,237696,111543479.0,88.0
986,Watership Down,1978,91,Animation,7.6,Martin Rosen,John Hubley,33656,232841485.0,64.0
992,The Jungle Book,1967,78,Animation,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0

In [15]:
# movies.groupby('Genre').["IMDB_Rating"].mean().sort_values(ascending=False)
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64